/* ════════════════════════════════════════════════════════════════════════
   antares-qa — "ask this portfolio" Q&A endpoint (Cloudflare Worker).

   POST /  with JSON body { "q": "<a question>" }
   →  { "answer": "<2–4 sentences>", "model": "<id>" }     on success
   →  { "error": "<reason>", "detail"? }                   on failure (4xx/5xx)

   The answer is generated by Workers AI but grounded ONLY in the site's own
   content — the Worker fetches https://<SITE>/llms-full.txt (≈5 KB, the
   canonical content dump) and hands it to the model as context. The system
   prompt forbids role-play and tells it to say so when the answer isn't in
   the context. No keys in the frontend; CORS is locked to the site origin
   (+ localhost for dev). The ⌘K palette's retrieval answers don't need this
   Worker — this just powers the "✨ ask this portfolio (AI answer)" option.

   Deploy: see wrangler.toml. Free tier covers a personal site's volume.
   ════════════════════════════════════════════════════════════════════════ */

const SITE = 'https://antaresyuan.site';
const LLMS_FULL_URL = `${SITE}/llms-full.txt`;
const MODEL = '@cf/meta/llama-3.1-8b-instruct-fast';   // alt: @cf/meta/llama-3.1-8b-instruct, @cf/meta/llama-3.3-70b-instruct-fp8-fast
const MAX_Q_CHARS = 500;
const MAX_CONTEXT_CHARS = 14000;

const SYSTEM_PROMPT = (context) => `You are a Q&A assistant for the personal website of Antares Yuan (an AI Product Manager). \
Answer the user's question using ONLY the CONTEXT below — it is the entire content of the site (projects shipped / in progress / planned, principles, contact). \
Rules:
- If the answer is not in the CONTEXT, say so plainly (e.g. "That isn't covered on the site.") — do not guess.
- Do NOT role-play as Antares. You are an assistant answering from their public data; refer to "Antares" in the third person.
- Be concise: 2–4 sentences, plain text, no markdown headings or bullet lists.
- No code, no links, no fabricated URLs.

CONTEXT:
${context}`;

function cors(origin) {
  const ok = origin === SITE
    || /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);
  return ok
    ? {
        'Access-Control-Allow-Origin': origin,
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Max-Age': '86400',
        Vary: 'Origin',
      }
    : { Vary: 'Origin' };   // no ACAO ⇒ a browser on another origin is blocked
}

function reply(obj, status, headers) {
  return new Response(JSON.stringify(obj), {
    status: status || 200,
    headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...(headers || {}) },
  });
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get('Origin') || '';
    const ch = cors(origin);

    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: ch });
    if (request.method !== 'POST') return reply({ error: 'POST a JSON body: { "q": "your question" }' }, 405, ch);

    // Optional per-IP rate limit (only if the RATE_LIMITER binding is configured — see wrangler.toml).
    if (env.RATE_LIMITER && typeof env.RATE_LIMITER.limit === 'function') {
      const ip = request.headers.get('CF-Connecting-IP') || 'anon';
      const { success } = await env.RATE_LIMITER.limit({ key: ip });
      if (!success) return reply({ error: 'rate limited — slow down a moment' }, 429, ch);
    }

    let body;
    try { body = await request.json(); } catch { return reply({ error: 'invalid JSON body' }, 400, ch); }
    const q = String((body && body.q) || '').trim().slice(0, MAX_Q_CHARS);
    if (!q) return reply({ error: 'missing "q" (the question)' }, 400, ch);

    // Grounding context: the site's own content dump. Cached at the edge.
    let context = '';
    try {
      const r = await fetch(LLMS_FULL_URL, { cf: { cacheTtl: 600, cacheEverything: true } });
      if (r.ok) context = (await r.text()).trim().slice(0, MAX_CONTEXT_CHARS);
    } catch { /* fall through */ }
    if (!context) return reply({ error: "couldn't load the site content to ground the answer" }, 502, ch);

    let out;
    try {
      out = await env.AI.run(MODEL, {
        messages: [
          { role: 'system', content: SYSTEM_PROMPT(context) },
          { role: 'user', content: q },
        ],
        max_tokens: 256,
        temperature: 0.3,
      });
    } catch (e) {
      return reply({ error: 'generation failed', detail: String((e && e.message) || e) }, 502, ch);
    }

    const answer = String((out && (out.response ?? out.result ?? '')) || '').trim();
    if (!answer) return reply({ error: 'the model returned an empty answer' }, 502, ch);
    return reply({ answer, model: MODEL }, 200, ch);
  },
};
