#!/bin/sh
# ─────────────────────────────────────────────────────────────────────
# antares-usage installer.  One line:
#
#   curl -fsSL https://antaresyuan.site/install.sh | sh
#
# Installs a small CLI that reads local Claude Code / Codex transcripts and
# posts daily token totals to the dashboard at antaresyuan.site. It downloads
# only the handful of files the agent needs — not the whole website — into
# ~/.local/share/antares-usage/cli, then drops an `antares-usage` command in
# ~/.local/bin.
#
# Why files-over-HTTP and not `git clone`: the agent is ~2.6k lines across 8
# files; cloning the site dragged down blog posts, images and templates the
# agent never touches. Same domain that serves the dashboard serves these.
#
# Re-runnable: re-fetches every file and rewrites the launcher. `antares-usage
# update` calls back here with setup skipped.
# ─────────────────────────────────────────────────────────────────────
set -eu

BASE="${ANTARES_USAGE_BASE:-https://antaresyuan.site}"
ROOT="${ANTARES_USAGE_HOME:-$HOME/.local/share/antares-usage/cli}"
BIN_DIR="${ANTARES_USAGE_BIN:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/antares-usage"

# The CLI's files, mirrored under $ROOT with the exact layout the scripts
# expect: each one resolves its siblings from its own directory (../.. →
# $ROOT), so the tree must be preserved verbatim or the first run fails deep
# inside path resolution.
FILES="
scripts/sync-usage.js
scripts/sync-usage.config.example.json
scripts/lib/usage-sources.js
scripts/lib/usage-aggregate.js
ops/setup-sync.sh
ops/launchagent/install.sh
ops/launchagent/com.antaresyuan.sync-usage.plist.template
ops/claude-hook/sync-usage-on-stop.sh
"

say() { printf '%s\n' "$*"; }
die() { printf 'install: %s\n' "$*" >&2; exit 1; }

[ "$(uname)" = "Darwin" ] || die "macOS only — the agent uses keychain + launchd."
command -v node >/dev/null 2>&1 || die "need node on PATH first (try 'brew install node')."
command -v curl >/dev/null 2>&1 || die "need curl."

say "── antares-usage — installing the usage sync CLI ──"
say "  from : $BASE"
say "  into : $ROOT"
say ""

# Download each file to a temp beside its destination, then move into place —
# a mid-download failure never leaves a half-written script that a later run
# would execute.
for rel in $FILES; do
  dest="$ROOT/$rel"
  mkdir -p "$(dirname "$dest")"
  tmp="$dest.tmp.$$"
  if ! curl -fsSL "$BASE/$rel" -o "$tmp"; then
    rm -f "$tmp"
    die "failed to download $rel from $BASE"
  fi
  mv -f "$tmp" "$dest"
  say "  fetched  $rel"
done

# HTTP downloads don't carry the +x bit; the entrypoints need it (the Stop
# hook is spawned by Claude Code's command runner, launchd execs the plist).
chmod +x "$ROOT/scripts/sync-usage.js" \
         "$ROOT/ops/setup-sync.sh" \
         "$ROOT/ops/launchagent/install.sh" \
         "$ROOT/ops/claude-hook/sync-usage-on-stop.sh"

# ── the `antares-usage` command ──────────────────────────────────────
# A thin dispatcher over the files just laid down. setup/sync/stats/doctor
# cover the lifecycle; any unknown verb is forwarded to sync-usage.js so a
# new flag works without reinstalling the launcher. Only $ROOT and $BASE are
# expanded now (the launcher must know where its files are and where to pull
# updates from); everything with a literal \$ stays for runtime.
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/sh
# antares-usage — CLI for the local AI-usage sync agent.
# Generated by $BASE/install.sh; edit that source, not this copy.
set -eu
ROOT="$ROOT"
BASE="$BASE"
SYNC="\$ROOT/scripts/sync-usage.js"
if [ \$# -gt 0 ]; then cmd="\$1"; shift; else cmd="help"; fi
case "\$cmd" in
  setup)  exec "\$ROOT/ops/setup-sync.sh" "\$@" ;;
  sync)   exec node "\$SYNC" "\$@" ;;
  stats)  exec node "\$SYNC" --stats "\$@" ;;
  doctor) exec node "\$SYNC" --doctor "\$@" ;;
  agent)  exec "\$ROOT/ops/launchagent/install.sh" "\$@" ;;
  update) exec sh -c "curl -fsSL '\$BASE/install.sh' | ANTARES_USAGE_NO_SETUP=1 sh" ;;
  help|-h|--help)
    cat <<USAGE
antares-usage — sync local Claude Code / Codex token usage to the dashboard

  antares-usage setup      set up this device (interactive; run once)
  antares-usage sync       upload the latest daily totals now
  antares-usage stats      local breakdown, no network
  antares-usage doctor     check config, secret and endpoint
  antares-usage agent ...  install | remove | status  the hourly LaunchAgent
  antares-usage update     re-download the CLI

Files: \$ROOT
USAGE
    ;;
  *) exec node "\$SYNC" "\$cmd" "\$@" ;;
esac
LAUNCH
chmod +x "$LAUNCHER"
say ""
say "  installed  $LAUNCHER"

# ── PATH note ────────────────────────────────────────────────────────
case ":$PATH:" in
  *":$BIN_DIR:"*) on_path=1 ;;
  *) on_path=0 ;;
esac
if [ "$on_path" = "0" ]; then
  say ""
  say "Note: $BIN_DIR is not on your PATH. Add it so 'antares-usage' resolves:"
  say "  echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc && source ~/.zshrc"
fi

# ── hand off to device setup ─────────────────────────────────────────
# Continue straight into setup when a real terminal is attached — this works
# even under `curl … | sh`, where the script arrives on stdin but /dev/tty is
# still the user's keyboard. With no tty (CI, `update`), stop and print the
# one command left.
if [ "${ANTARES_USAGE_NO_SETUP:-0}" = "1" ]; then
  say ""
  say "Done. Files refreshed."
elif [ -r /dev/tty ]; then
  say ""
  say "Continuing into device setup…"
  say ""
  "$ROOT/ops/setup-sync.sh" </dev/tty || die "setup did not finish — re-run it with: antares-usage setup"
else
  say ""
  say "Next: run  antares-usage setup   (interactive — sets this device's slot + secret)"
fi
