#!/usr/bin/env node
/* ════════════════════════════════════════════════════════════════════════
   build-glyphs.js — a one-page gallery of the doodle glyphs, at /glyphs.

   Reads the GLYPHS object out of scripts/doodle.js (regex + eval — tolerant:
   if it can't parse it, it logs a note and skips, leaving the build fine).
   Wired into scripts/build.js. The /admin/ Doodles "Icon" field hint links here.
   ════════════════════════════════════════════════════════════════════════ */
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

try {
  const src = fs.readFileSync(path.join(root, 'scripts/doodle.js'), 'utf8');
  const m = src.match(/var GLYPHS = (\{[\s\S]*?\n  \});/);
  if (!m) { console.log('  (skip /glyphs — couldn’t find GLYPHS in doodle.js)'); }
  else {
    // eslint-disable-next-line no-eval
    const GLYPHS = eval('(' + m[1] + ')');
    const names = Object.keys(GLYPHS);
    const cards = names.map((n) =>
      `    <figure><div class="g"><svg viewBox="0 0 24 24" aria-hidden="true">${GLYPHS[n]}</svg></div><figcaption>${n}</figcaption></figure>`
    ).join('\n');
    const html = `<!DOCTYPE html>
<!-- GENERATED by scripts/build-glyphs.js — the doodle-glyph gallery. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Doodle glyphs</title>
<meta name="robots" content="noindex">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<style>
  :root { color-scheme: dark; }
  body { margin: 0; padding: 48px 24px 72px; background: #14130D; color: #C9C4B3; font: 14px/1.55 ui-monospace, "JetBrains Mono", Menlo, monospace; }
  main { max-width: 760px; margin: 0 auto; }
  h1 { color: #F7F4ED; font-size: 22px; font-weight: 600; letter-spacing: -.01em; margin: 0 0 8px; }
  p { color: #8D8979; margin: 0 0 40px; }
  a { color: #8DA2FF; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(116px, 1fr)); gap: 16px; }
  figure { margin: 0; text-align: center; }
  .g { background: #1C1A12; border-radius: 12px; padding: 22px; }
  .g svg { display: block; width: 100%; height: auto; color: #F5C518; filter: drop-shadow(0 0 6px rgba(245,197,24,.35)); }
  figcaption { margin-top: 10px; color: #8D8979; }
</style>
</head>
<body>
<main>
  <h1>Doodle glyphs</h1>
  <p>The icons available for special-day doodles — set one in <a href="/admin/">/admin/</a> → <strong>Doodles</strong> (the “Icon” field), or upload a custom SVG there. Want a glyph that isn’t here? Ask, and it’ll be added.</p>
  <div class="grid">
${cards}
  </div>
</main>
</body>
</html>
`;
    fs.writeFileSync(path.join(root, 'glyphs.html'), html);
    console.log(`✓ wrote glyphs.html    (${names.length} doodle glyphs)`);
  }
} catch (e) {
  console.log('  (skip /glyphs — ' + ((e && e.message) || e) + ')');
}
